Проектная работа. Группа 10. Подготовка данных: Кросс валидация. Хуснутдинов Эдуард Ринатович. Нуман Ахмед. Эспиноза Ортис Хуан Карлос

# Кросс-валидация - введение

В этой серии лекций мы подробно рассмотрим различные методы кросс-валидации, а также обсудим общую идею кросс-валидации. Хорошую документацию по этой теме можно почитать вот здесь: https://scikit-learn.org/stable/modules/cross_validation.html

## Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Пример данных

In [2]:
df = pd.read_csv("X_prepared_sample.csv")

In [3]:
df.head()

,city_development_index,experience,last_new_job,training_hours,target,no_job_info,is_university_enrolled,relevent_experience_No relevent experience,city_city_10,city_city_100,...,education_level_5,major_discipline_Business Degree,major_discipline_Humanities,major_discipline_No Major,major_discipline_Other,major_discipline_STEM,major_discipline_not_stated,gender_Male,gender_Other,gender_not_stated
0,0.920,21.0,1.0,36.0,1.0,1,0,False,False,False,...,False,False,False,False,False,True,False,True,False,False
1,0.776,15.0,5.0,47.0,0.0,0,0,True,False,False,...,False,False,False,False,False,True,False,True,False,False
2,0.624,5.0,0.0,83.0,0.0,1,1,True,False,False,...,False,False,False,False,False,True,False,False,False,True
3,0.789,0.0,0.0,52.0,1.0,0,1,True,False,False,...,False,True,False,False,False,False,False,False,False,True
4,0.767,21.0,4.0,8.0,0.0,0,0,False,False,False,...,False,False,False,False,False,True,False,True,False,False

----
----
----
## Разбиваем данные на обучающий и тестовый наборы данных - Train | Test Split

0. Очищаем и масштабируем данные X и y (при необходимости)
1. Разбиваем данные на обучающий и тестовый наборы данных - как для X, так и для y
2. Обучаем объект Scaler на обучающих данных X
3. Применяем масштабирование (scale) для тестовых данных X
4. Создаём модель
5. Обучаем модель на обучающих данных X
6. Оцениваем модель на тестовых данных X (создавая предсказания и сравнивая их с Y_test)
7. Уточняем параметры модели, повторяя шаги 5 и 6

In [4]:
## Создаём X и y
X = df.drop('target',axis=1)
y = df['target']

# Разбиение на TRAIN и TEST
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# Масштабирование данных - SCALE DATA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

**Создаём модель**

In [5]:
from sklearn.linear_model import Ridge

In [6]:
# Мы осознанно указываем неудачное значение Alpha!
model = Ridge(alpha=100)

In [7]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [8]:
y_pred = model.predict(X_test)

**Оценка модели (evaluation)**

In [9]:
from sklearn.metrics import mean_squared_error

In [10]:
mean_squared_error(y_test,y_pred)

0.14550502063610635

**Уточняем параметры и заново оцениваем модель**

In [11]:
model = Ridge(alpha=1)

In [12]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [13]:
y_pred = model.predict(X_test)

**Повторная оценка**

In [14]:
mean_squared_error(y_test,y_pred)

0.2493287812277639

## Лучше использовать alpha=100.

----
----
----
## Обучение - валидация - тестирование (Train | Validation | Test Split Procedure)

Этот подход ещё называют методом с задержкой ("hold-out"), потому что здесь мы не настраиваем параметры модели на финальном тестовом наборе данных, а используем тестовые данные *только* для оценки финального результата.

0. Очищаем и масштабируем данные X и y (при необходимости)
1. Разбиваем данные на обучающий, оценочный и тестовый наборы данных - как для X, так и для y
2. Обучаем объект Scaler на обучающих данных X
3. Масштабируем (scale) оценочные данные X
4. Создаём модель
5. Обучаем модель на обучающих данных X
6. Оцениваем модель на оценочных данных X (создавая предсказания и сравнивая их с Y_eval)
7. Уточняем параметры модели, повторяя шаги 5 и 6
8. Вычисляем финальные метрики на тестовом наборе данных (после этого уже нельзя возвращаться и делать уточнения!)

In [15]:
## Создаём X и y
X = df.drop('target',axis=1)
y = df['target']

In [16]:
###############################################################################################
#### Вызываем SPLIT дважды! Здесь мы создаём три набора данных - TRAIN, VALIDATION и TEST  #########
###############################################################################################
from sklearn.model_selection import train_test_split

# 70% данных определяем в обучающий набор, остальные 30% откладываем в сторону
X_train, X_OTHER, y_train, y_OTHER = train_test_split(X, y, test_size=0.3, random_state=101)

# Оставшиеся 30% разбиваем на оценочный и тестовый наборы данных
# Каждый будет по 15% от исходного набора данных 
X_eval, X_test, y_eval, y_test = train_test_split(X_OTHER, y_OTHER, test_size=0.5, random_state=101)

In [17]:
# Проверяем
len(df)

200

In [18]:
len(X_train)

140

In [19]:
len(X_eval)

30

In [20]:
len(X_test)

30

In [21]:
# Масштабируем данные (SCALE)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_eval = scaler.transform(X_eval)
X_test = scaler.transform(X_test)

**Создаём модель**

In [22]:
from sklearn.linear_model import Ridge

In [23]:
# Мы осознанно указываем неудачное значение Alpha!
model = Ridge(alpha=100)

In [24]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [25]:
y_eval_pred = model.predict(X_eval)

**Оценка модели (Evaluation)**

In [26]:
from sklearn.metrics import mean_squared_error

In [27]:
mean_squared_error(y_eval,y_eval_pred)

0.1294849033734898

**Уточняем параметры и повторно оцениваем модель**

In [28]:
model = Ridge(alpha=1)

In [29]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [30]:
y_eval_pred = model.predict(X_eval)

**Ещё раз оцениваем модель**

In [31]:
mean_squared_error(y_eval,y_eval_pred)

0.21973697323676908

## Лучше использовать alpha=100.

**Вычисляем финальные метрики на тестовом наборе данных (после этого уже нельзя возвращаться и делать уточнения!)**

In [32]:
y_final_test_pred = model.predict(X_test)

In [33]:
mean_squared_error(y_test,y_final_test_pred)

0.27892058921875856

----
----
----
## Кросс-валидация с помощью cross_val_score

----

<img src="grid_search_cross_validation.png">

----

In [34]:
## Создаём X и y
X = df.drop('target',axis=1)
y = df['target']

# Разбиение на TRAIN и TEST
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# Масштабирование данных (SCALE)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [35]:
model = Ridge(alpha=100)

In [36]:
from sklearn.model_selection import cross_val_score

In [37]:
# Варианты оценки модели:
# https://scikit-learn.org/stable/modules/model_evaluation.html
scores = cross_val_score(model,X_train,y_train,
                         scoring='neg_mean_squared_error',cv=5)

In [38]:
scores

array([-0.1940991 , -0.15126691, -0.22235151, -0.19997792, -0.17586804])

In [39]:
# Среднее значение MSE scores (делаем это значение положительным)
abs(scores.mean())

np.float64(0.1887126958590254)

**Уточняем модель на основе метрик**

In [40]:
model = Ridge(alpha=1)

In [41]:
# Варианты оценки модели:
# https://scikit-learn.org/stable/modules/model_evaluation.html
scores = cross_val_score(model,X_train,y_train,
                         scoring='neg_mean_squared_error',cv=5)

In [42]:
# Среднее значение MSE scores (делаем это значение положительным)
abs(scores.mean())

np.float64(0.3028567003767112)

**Вычисляем финальные метрики на тестовом наборе данных (после этого уже нельзя возвращаться и делать уточнения!)**

In [43]:
# Сначала нужно обучить модель!
model.fit(X_train,y_train)

Ridge(alpha=1)

In [44]:
y_final_test_pred = model.predict(X_test)

In [45]:
mean_squared_error(y_test,y_final_test_pred)

0.2493287812277639

----
----
----

# Кросс-валидация с помощью cross_validate

Функция cross_validate отличается от cross_val_score двумя аспектами:

эта функция позволяет использовать для оценки несколько метрик;

она возвращает не только оценку на тестовом наборе (test score), но и словарь с замерами времени обучения и скоринга, а также - опционально - оценки на обучающем наборе и объекты estimator.

В случае одной метрики для оценки, когда параметр scoring является строкой string, вызываемым объектом callable или значением None, ключи словаря будут следующими:
        
        - ['test_score', 'fit_time', 'score_time']

А в случае нескольких метрик для оценки, возвращаемый словарь будет содержать следующие ключи:

    ['test_<scorer1_name>', 'test_<scorer2_name>', 'test_<scorer...>', 'fit_time', 'score_time']

return_train_score по умолчанию принимает значение False, чтобы сэкономить вычислительные ресурсы. Чтобы посчитать оценки на обучающем наборе, достаточно установить этот параметр в значение True.

In [46]:
## Создаём X и y
X = df.drop('target',axis=1)
y = df['target']

# Делаем разбиение на TRAIN и TEST
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# Масштабируем данные (SCALE)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [47]:
model = Ridge(alpha=100)

In [48]:
from sklearn.model_selection import cross_validate

In [49]:
# Варианты оценки модели:
# https://scikit-learn.org/stable/modules/model_evaluation.html
scores = cross_validate(model,X_train,y_train,
                         scoring=['neg_mean_absolute_error','neg_mean_squared_error'],cv=5)

In [50]:
scores

{'fit_time': array([0.00300646, 0.00200653, 0.00257158, 0.0025382 , 0.00347733]),
 'score_time': array([0.00206709, 0.00183606, 0.00212765, 0.00217056, 0.00171709]),
 'test_neg_mean_absolute_error': array([-0.37159696, -0.32076345, -0.3978829 , -0.33548405, -0.3599119 ]),
 'test_neg_mean_squared_error': array([-0.1940991 , -0.15126691, -0.22235151, -0.19997792, -0.17586804])}

In [51]:
pd.DataFrame(scores)

,fit_time,score_time,test_neg_mean_absolute_error,test_neg_mean_squared_error
0,0.003006,0.002067,-0.371597,-0.194099
1,0.002007,0.001836,-0.320763,-0.151267
2,0.002572,0.002128,-0.397883,-0.222352
3,0.002538,0.002171,-0.335484,-0.199978
4,0.003477,0.001717,-0.359912,-0.175868

In [52]:
pd.DataFrame(scores).mean()

fit_time                        0.002720
score_time                      0.001984
test_neg_mean_absolute_error   -0.357128
test_neg_mean_squared_error    -0.188713
dtype: float64

**Уточняем модель на основе метрик**

In [53]:
model = Ridge(alpha=1)

In [54]:
# Варианты оценки модели:
# https://scikit-learn.org/stable/modules/model_evaluation.html
scores = cross_validate(model,X_train,y_train,
                         scoring=['neg_mean_absolute_error','neg_mean_squared_error'],cv=5)

In [55]:
pd.DataFrame(scores)

,fit_time,score_time,test_neg_mean_absolute_error,test_neg_mean_squared_error
0,0.003386,0.001567,-0.530170,-0.400714
1,0.002258,0.002016,-0.408214,-0.239720
2,0.002912,0.002000,-0.469886,-0.329953
3,0.002794,0.001062,-0.427039,-0.307148
4,0.002200,0.001403,-0.400533,-0.236749

In [56]:
pd.DataFrame(scores).mean()

fit_time                        0.002710
score_time                      0.001610
test_neg_mean_absolute_error   -0.447168
test_neg_mean_squared_error    -0.302857
dtype: float64

**Вычисляем финальные метрики на тестовом наборе данных (после этого уже нельзя возвращаться и делать уточнения!)**

In [57]:
# Сначала нужно обучить модель!
model.fit(X_train,y_train)

Ridge(alpha=1)

In [58]:
y_final_test_pred = model.predict(X_test)

In [59]:
mean_squared_error(y_test,y_final_test_pred)

0.2493287812277639

Вывод: Ridge(alpha=100) показывает лучшие результаты, чем Ridge(alpha=1), поскольку значения MSE у неё ниже. Кросс-валидация подтверждает, что более сильная регуляризация в этом примере даёт более стабильное и качественное качество, а использование отдельной валидации или cross-validation позволяет оценивать модель надёжнее, чем простой train/test split